services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./data/postgres:/var/lib/postgresql/data
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
