services:
  tippecanoe:
    build:
      context: https://github.com/felt/tippecanoe.git
    command: echo "tippecanoe loaded" # override the default command which runs the tests
    volumes:
      - ./data:/data
