name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: timeout 240 docker compose exec -T app pg_isready -h localhost -p 5432

      - name: Build project
        run: docker compose exec -T app npm run build

      - name: Type check
        run: docker compose exec -T app npm run check-types

      - name: Run tests
        run: docker compose exec -T app npm test
        env:
          CI: true

      - name: Cleanup
        if: always()
        run: docker compose down
