name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..60}; do
            if docker compose exec -T app pg_isready -U postgres 2>/dev/null; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL... ($i/60)"
            sleep 2
          done

      - name: Build project
        run: docker compose exec -T app npm run build

      - name: Type check
        run: docker compose exec -T app npm run check-types

      - name: Run tests
        run: docker compose exec -T app npm test
        env:
          CI: true

      - name: Cleanup
        if: always()
        run: docker compose down
